spring:
  application:
    name: ride-sharing


  datasource:
    url: jdbc:postgresql://localhost:5432/location
    username: postgres
    password: admin


  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

security:
  secret: aldsjgfhaskldjfgaskdgfuwiegr389756tadfbskjhdfgasfasdfa
  expire: 450000

servlet:


logging:
  level:
    root: INFO
    org.hibernate: DEBUG
    io.aygh7.location_system: DEBUG